using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace HtmlParser.Test
{
    public class CompatibilityModeTest
    {
        [Fact]
        public void Test_CompatibilityMode_NoQuirks()
        {
            var data = new[]
            {
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 //en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en"" ""http://www.w3.org/tr/rec-html40/strict.dtd"">",
            @"<!doctype html public '-//w3c//dtd xhtml 1.0 strict//en' 'http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd'>",
            @"<!doctype html public ""-//sq//dtd html 2.0 + all extensions//en"" ""hmpro3.dtd"">",
            @"<!doctype html public ""-//ietf//dtd html 4.0//en"">",
            @"<!doctype html public ""-//softquad//dtd hotmetal pro 4.0::19970714::extensions to html 4.0//en"" ""hmpro4.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 //en"">",
            @"<!doctype html public ""-//ietf//dtd html 3.2 level 3.2//en"">",
            @"<!doctype html public ""-//softquad software//dtd hotmetal pro 5.0::19981217::extensions to html 4.0//en"" ""hmpro5.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 final//en"">",
            @"<!doctype html public ""-//wc3//dtd html 4.0//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"" >",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//softquad//dtd hotmetal pro 5.0::19980907::extensions to html 4.0//en"" ""hmpro5.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//de"">",
            @"<!doctype html public ""-//w3c//dtd html 4.1 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/2000/rec-xhtml1-20000126/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//wc3//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//softquad//dtd hotmetal pro 5.0::19980626::extensions to html 4.0//en"" ""hmpro5.dtd"">",
            @"<!doctype html public ""-//softquad//dtd hotmetal pro 4.0::19970916::extensions to html 4.0//en"" ""hmpro4.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3o//dtd w3 html 2.0//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 strict//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.1 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/strict.dtd"">",
            @"<!doctype html public ""-//ietf//dtd html//en//3.2"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 strict//en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html system ""html.dtd"">",
            @"<!doctype html>",
            @"<!doctype html public ""+//isbn 82-7640-037::www//dtd html//en//2.0"" ""html.dtd"">",
            @"<!doctype html public ""-//w30//dtd w3 html2.0//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//it"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml2/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""xhtml11.dtd"">",
            @"<!doctype html public ""-//softquad//dtd hotmetal pro 5.0::19981022::extensions to html 4.0//en"" ""hmpro5.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 strict//en"">",
            @"<!doctype html public ""-//wc3//dtd html 3.2//en"">",
            @"<!doctype html public ""-//softquad//dtd html 2.0 + extensions for hotmetal light 3.0 19960703//en"" >",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//es"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//fr"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en""""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3o/dtd html//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//it"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//ru"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/1999/rec-html401-19991224/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/2002/rec-xhtml1-20020801/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//wc3//dtd html 4.01 transitional//en"">",
            @"<!doctype html public ""-//ibm//dtd hpb html//en"">",
            @"<!doctype html public ""-//softquad//dtd html 3.2 + extensions for hotmetal pro 3.0(u) 19961211//en"" ""hmpro3.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 3.0//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 draft//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//de"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//fr"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//it"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/html40/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/rec-html40/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//de"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//de"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//fr"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public""-//w3c//dtd html 4.0//en"">",
            @"<!doctype html public ""-//softquad//dtd hotmetal pro 4.0::19980408::extensions to html 4.0 for miva//en"" ""hmpro4.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 3//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//cz"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//es"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//de"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3c.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//fr"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//es"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml basic 1.0//en"" ""http://www.w3.org/tr/xhtml-basic/xhtml-basic10.dtd"">",
            @"<!doctype html public ""-//w3c/dtd html 3.2//en"">",
            @"<!doctype html public ""-//wapforum//dtd xhtml mobile 1.0//en"" ""http://www.wapforum.org/dtd/xhtml-mobile10.dtd"">",
            @"<!doctype html public ""-//wc3//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public '-//w3c//dtd html 4.01//en' 'http://www.w3.org/tr/html4/strict.dtd'>",
            @"<!doctype html public """">",
            @"<!doctype html public ""-//ietf//dtd html//en//4.0"">",
            @"<!doctype html public ""-//sq//dtd html 2.0 + alle erweiterungen//en"" ""hmpro3.dtd"">",
            @"<!doctype html public ""-//w30//dtd w3 html 3.2//en"">",
            @"<!doctype html public ""-//w3c//dtd html 3.0 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 final//de"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2//it"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional //en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//nl"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//pl"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 strict //en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//ar"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//he"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//nl"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//ru"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//tr"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/html4/dtd/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/html4/transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/rec-html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en""""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.1 frameset//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 nearly transitional//en"" """">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//da"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/2000/rec-xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//nl"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional //en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//em"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//it"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/2001/rec-xhtml11-20010531/dtd/xhtml11-flat.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"" >",
            @"<!doctype html public ""-//w3c//html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3o//dtd w3 html 3.2//en"">",
            @"<!doctype html public ""-//wc3//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-/w3c/dtd html 4.01 transitional/en"">",
            @"<!doctype html public ""-w3//dtd html 4.0 final//en"">",
            @"<!doctype html public '-//w3c//dtd html 4.0 //en'>",
            @"<!doctype html public '-//w3c//dtd xhtml 1.0 strict//en' ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public '-//w3c//dtd xhtml 1.0 strict//en' 'dtd/xhtml1-strict.dtd'>",
            @"<!doctype html public '-//w3c//dtd xhtml 1.1//en' 'http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd'>",
            @"<!doctype html public "" -//w3c//dtd html 4.0 transitional//en "">",
            @"<!doctype html public "" -//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tr/html14/frameset.dtd"">",
            @"<!doctype html public "" -//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html public ""&#150;//w3c//dtd html 3.2//en"">",
            @"<!doctype html public ""&#150;//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec&#150;html40/loose.dtd"">",
            @"<!doctype html public ""+//isbn 82-7640-037::www//dtd html//en//2.0"" ""html.dtd"" >",
            @"<!doctype html public ""- //w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html public ""- w3c dtd xhtml 1.0 transitional en"" ""http: www.w3.org tr xhtml1 dtd xhtml1-transitional.dtd"" >",
            @"<!doctype html public ""-//att//dtd mozilla html 4.0//en"">",
            @"<!doctype html public ""-//extensions to html 4.0//en"">",
            @"<!doctype html public ""-//i3c//dtd html 4.0 transitional//en"">",
            @"<!doctype html public ""-//idf//dtd html 3.2//fr"">",
            @"<!doctype html public ""-//ieft//dtd html 4.0//en"">",
            @"<!doctype html public ""-//ieft//dtd html//en"">",
            @"<!doctype html public ""-//ieft//dtd html//en//2.0"">",
            @"<!doctype html public ""-//ietf//dtd html 2.1 experimental//en"">",
            @"<!doctype html public ""-//ietf//dtd html 2.1//en"">",
            @"<!doctype html public ""-//ietf//dtd html 2.2//en"">",
            @"<!doctype html public ""-//ietf//dtd html 3.2//en//"">",
            @"<!doctype html public ""-//ietf//dtd html 3.2//ru"">",
            @"<!doctype html public ""-//ietf//dtd html 4.0 draft//en"">",
            @"<!doctype html public ""-//ietf//dtd html 4.0//it"">",
            @"<!doctype html public ""-//ietf//dtd html 4.01 frameset//en"">",
            @"<!doctype html public ""-//ietf//dtd html//en//"">",
            @"<!doctype html public ""-//ietf//dtd html//en//4.1"">",
            @"<!doctype html public ""-//ietf//dtd html//en//rus//rom"">",
            @"<!doctype html public ""-//ietf//dtd html//fi"">",
            @"<!doctype html public ""-//ietf//dtd html//it"">",
            @"<!doctype html public ""-//ietf/dtd html 3.0//en"">",
            @"<!doctype html public ""-//lidovky//dtd html 4//en"" ""http://g.lidovky.cz/dtd/n3_uni.dtd"">",
            @"<!doctype html public ""-//netscape corp.//dtd html plus tables//en"" ""html-net.dtd"">",
            @"<!doctype html public ""-//netscape//dtd html"">",
            @"<!doctype html public ""-//securshred//dtd xhtml-with target//en"" ""http://www.securshred.com/dtd/xhtml-target.dtd"">",
            @"<!doctype html public ""-//simotime//dtd html 4.0 transitional//en"" ""hmpro6.dtd"">",
            @"<!doctype html public ""-//softquad software//dtd hotmetal pro 5.0::19981130::extensions to html 4.0//en"" ""hmpro5.dtd"">",
            @"<!doctype html public ""-//softquad//dtd hotmetal pro 4.0::19970617::extensions to html 3.2//en"" ""hmpro4.dtd"">",
            @"<!doctype html public ""-//softquad//dtd hotmetal pro 6.0::19970916::extensions to html 4.0//de"" ""hmpro4.dtd"">",
            @"<!doctype html public ""-//softquad//dtd html 3.2 + extensions for hotmetal pro 3.0 19961211//en"" ""hmpro3.dtd"">",
            @"<!doctype html public ""-//sq//dtd html 2.0 + all extensions//en"">",
            @"<!doctype html public ""-//tigris//dtd xhtml 1.0 transitional//en"" ""http://style.tigris.org/tigris_transitional.dtd"">",
            @"<!doctype html public ""-//tnet//dtd html 3 extended 960415//en"">",
            @"<!doctype html public ""-//w#c//dtd html 3.2 draft//en"">",
            @"<!doctype html public ""-//w3//dtd html 3.2 final//en"">",
            @"<!doctype html public ""-//w30//dtd w3 html 2.0//en"">",
            @"<!doctype html public ""-//w3c// dtd html 4.0 transitional//en"">",
            @"<!doctype html public ""-//w3c//d td xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//d xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dd html 4.0 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtc html 3.2//en"">",
            @"<!doctype html public ""-//w3c//dtd 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd htm 3.2//en"">",
            @"<!doctype html public ""-//w3c//dtd html 1.0 loose//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 1.0 transitional//en"" ""http://www.w3.org/tr/html1/dtd/html1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 2.0 //de"">",
            @"<!doctype html public ""-//w3c//dtd html 2.0 //en"">",
            @"<!doctype html public ""-//w3c//dtd html 3.0 //en"">",
            @"<!doctype html public ""-//w3c//dtd html 3.0 transitional//en""""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 3.0 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 3.01 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 final//efn"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 final//es"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 final//it"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2//de"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2//eo"">",
            @"<!doctype html public ""-//w3c//dtd html 4 //en"">",
            @"<!doctype html public ""-//w3c//dtd html 4 final//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4 trans//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4,0 final//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 //en"" ""http://www.w3.org/tr/html4/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 //en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 //it"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 final//fr"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frame//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset //en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset// en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//de"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en//"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//fr"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 strict//en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 tansitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 trabgcolr nsitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transisional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transistional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional //en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//de"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//el"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en//"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//fr"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//he"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//hu"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//ita"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//lt"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//se"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//sp"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//tr"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitonal//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 trasitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0// en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//da"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//de"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//em"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en"" ""http://www.w3.org.tr/rec-html40/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en"" ""http://www.w3.org/tr/html4/strict.dtd"" >",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en"" ""http://www.w3.org/tr/rec-html40/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en"" ""http://www.w3.org/tr/wd-html-in-xml/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en//"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0//pl"">",
            @"<!doctype html public ""-//w3c//dtd html 4.00 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 //en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 final//cz"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 frameset"" ""http://www.w3.org/tr/html4/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 frameset//de"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 strict//de"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 strict//en"" ""http://home.datacomm.ch/neugut"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 strict//en""""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 tables transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//cyr"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//e n"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en "" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en conova"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//es"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//no"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//pl"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//rus"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//sk"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional::en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitonal//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transsitional//en"" ""http://www.ratpak.de/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//de"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http:// www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/1999/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/html4/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/html4/strict.dtd"" >",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/html4/transitional"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/html401/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" ""http://www.w3c.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//nl"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.02 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.1 frameset//en"" ""http://www.w3.0rg/tr/html4/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.1 frameset//en"" >",
            @"<!doctype html public ""-//w3c//dtd html 4.1 transitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.1//en"" ""http://www.w3.org/tr/html40/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.o final//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.x transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html ?.?//en"">",
            @"<!doctype html public ""-//w3c//dtd html proprietary//en"">",
            @"<!doctype html public ""-//w3c//dtd html"">",
            @"<!doctype html public ""-//w3c//dtd html4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd phpl 4.0 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd thml 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd valign=top padding=0 border-width=0 xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd valign=top padding=0 border-width=0/xhtml1-transitional.dtd valign=top padding=0 border-width=0"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 0.8 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 standart//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//de"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""../www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http:// www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.3c.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.britishinstitute.net/common/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.imageservice.net/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/1999/rec-html401-19991224/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/2000/rec xhtml1-20000126/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/html/dtd/xhtml-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/ dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtm1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml 1.0 strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1 transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1- strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict/dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtmll/dtd/xhtmll-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""https://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//it"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//nl"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//uk"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transational//en"" ""dtd/xhtml1-transational.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//dut"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//enc"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//fr"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//gr"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//ru"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//sv"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//tr"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitionalt//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitionnal//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitionnal.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1 plus mathml 2.0//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1 plus target//en"" ""/media/templatedesign_media/xml/coba.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1 strict//en"" ""http://www.w3.org/tr/xhtml11/dtd/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1 strict//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1 strict//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1 transitional//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//da"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//de"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" "" http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd "">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1.1.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11_flat.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml11/td/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//fr"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.1//it"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 4.0 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 4.01 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml basic 1.0//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml+rdfa 1.0//en"" ""http://www.w3.org/markup/dtd/xhtml-rdfa-1.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml1.0 transitional//en"" ""http://www.w3.org/tr/xhtml/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd'oa html 4.01 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd// html 4.0 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c/dtd html 4.0 draft//en"">",
            @"<!doctype html public ""-//w3c/dtd html 4.0 transitional//en"">",
            @"<!doctype html public ""-//w3c/dtd html 4.0//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c/dtd html 4.01 transitional//en"">",
            @"<!doctype html public ""-//w3c/dtd html 4.01 transitional/en"">",
            @"<!doctype html public ""-//w3c/dtd html 4.01//en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c/dtd html 4.1 frameset//en"">",
            @"<!doctype html public ""-//w3c/dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/transitional.dtd"">",
            @"<!doctype html public ""-//w3c/dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c/dtd/xhtml 1.0 strict//en"" ""http://www.w3c.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3cimagestd html 4.0 transitional//en"">",
            @"<!doctype html public ""-//w3o//dtd html 3.0//en"">",
            @"<!doctype html public ""-//w3w//dtd html 3.2//en"">",
            @"<!doctype html public ""-//wc3//dtd html 4.0 //en"">",
            @"<!doctype html public ""-//wc3//dtd html 4.0 frameset//en"">",
            @"<!doctype html public ""-//wc3//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w§c//dtd html 4.01 transitional//en"">",
            @"<!doctype html public ""-/w3c/dtd html 4.01 transitional/en"" ""http:/www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-/w3c/dtd xhtml 1.0 transitional/en"" ""http:/www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-/w3c/dtd xhtml 1.1/en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype html public ""-w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/transitional.dtd"">",
            @"<!doctype html public ""./w3./dtd html 4.0 transitiona./en"">",
            @"<!doctype html public ""//ietf//dtd html 3.2 draft//en"">",
            @"<!doctype html public ""//ietf//dtd html//en"">",
            @"<!doctype html public ""//w3c//dtd html 4.0 // en"">",
            @"<!doctype html public ""//w3c//dtd html 4.0 strict//en"">",
            @"<!doctype html public ""//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""//w3c//dtd html 4.0 transitional//en"">",
            @"<!doctype html public ""//w3c//dtd html 4.01 frameset//en"">",
            @"<!doctype html public ""=/w3c//dtd html 4.0 frameset//en"">",
            @"<!doctype html public ""_//w3c/dtd html 4.0 transitional//en"">",
            @"<!doctype html public ""enhanced html document"">",
            @"<!doctype html public ""guest house,jersey,haven,guest house,accommodation,jersey,channel islands,saint helier,british "">",
            @"<!doctype html public ""hmpro4.dtd"">",
            @"<!doctype html public ""html 3.0"">",
            @"<!doctype html public ""html 3.2"">",
            @"<!doctype html public ""html 4.01 transitional"">",
            @"<!doctype html public ""html.dtd"">",
            @"<!doctype html public ""html4.0"">",
            @"<!doctype html public ""xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""¡¡- //w3c//dtd html 4.0 transitional//en"">",
            @"<!doctype html public '-//ietf//dtd html 3.0 strict//en' >",
            @"<!doctype html public '-//sq//dtd html 2.0 + all extensions//en'>",
            @"<!doctype html public '-//w3c//dtd html 4.0 transitional//fr'>",
            @"<!doctype html public '-//w3c//dtd html 4.0//en' >",
            @"<!doctype html public '-//w3c//dtd html 4.01 //en' 'http://www.w3.org/tr/xhtml11/dtd/xhtml-transitional.dtd'>",
            @"<!doctype html public '-//w3c//dtd html 4.01 strict//en'>",
            @"<!doctype html public '-//w3c//dtd html 4.01 transitional//en http://www.w3.org/tr/html4/loose.dtd'>",
            @"<!doctype html public '-//w3c//dtd xhtml 1.0 strict//en http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd'>",
            @"<!doctype html public '-//w3c//dtd xhtml 1.0 strict//en' 'http://www.w3.org/tr/xhtml1/dtd/xhtml10-strict.dtd'>",
            @"<!doctype html public"" -//w3c//dtd xhtml 4.0 transitional//en"">",
            @"<!doctype html public""-//w#c//dtd html 3.2 final// \en"">",
            @"<!doctype html public""-//w3/dtd html 4.0 frameset//en"" ""http://www.w3.org/tr/rec-html40/frameset.dtd"">",
            @"<!doctype html public""-//w3c//dtd html 4.0 transitional??en"">",
            @"<!doctype html public""-//w3c/dtd html 3.2//en"">",
            @"<!doctype html system ""hmpro4.dtd"">",
            @"<!doctype html system ""http://www.fragerco.com/fghtml4.dtd"">",
            @"<!doctype html system ""http://www.ptouchlabel.co.uk/dtd/html4-framesetplus.dtd"">",
            @"<!doctype html system ""http://www.uni-graz.at/~katzer/html40-gk-ext.dtd"">",
            @"<!doctypehtml public ""-//w3c//dtd html 4.0//en"">"
            };

            foreach (var doctype in data) {
                var actual = CompatibilityMode.GetCompatibilityModeFromDoctype(doctype.Trim(new[] { '<', '>', '!' }));
                Assert.Equal(CompatibilityModeDoctype.NoQuirks, actual);
            }
        }


        [Fact]
        public void Test_CompatibilityMode_LimitedQuirks()
        {
            var data = new[]
            {
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tr/html4/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 frameset//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/1999/rec-html401-19991224/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3c.org/tr/1999/rec-html401-19991224/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html40/strict.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/2000/rec-xhtml1-20000126/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en""""http://www.w3.org/tr/html4/loose.dtd"">",
            @"!doctype html public '-//w3c//dtd xhtml 1.0 transitional//en' 'http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd'>",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http:\\www.w3.org\tr\html\loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html40/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"" >",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd "">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html401/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"" >",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/2002/rec-xhtml1-20020801/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tr/1999/rec-html401-19991224/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""hmpro6.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 frameset//en"" ""dtd/xhtml1-frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1- transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3c.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en""""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public '-//w3c//dtd html 4.01 transitional//en' 'http://www.w3.org/tr/html4/loose.dtd'>",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www/w3.org/tr/xhtml/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/dtd/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" >",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/1999/rec-html40119991224/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/rec-html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""dtd/xhtml-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/1999/pr-xhtml1-19991210/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/html1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml2/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""xhtml1-transitional.dtd"">",
            @"!doctype html public '-//w3c//dtd xhtml 1.0 transitional//en' 'http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd' >",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tr/rec-html40/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3c.org/tr/1999/rec-html401-19991224/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""c:\program files\softquad\xmetal 2\rules\loose-4.01.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.or g/tr/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/xhtml4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3c.org/tr/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""dtd/xhtml1-transitional.dtd"" >",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/1999/xhtml/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/2000/rec-xhtml1-200000126/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-trans.dtd"">",
            @"!doctype html public '-//w3c//dtd xhtml 1.0 transitional//en' 'dtd/xhtml1-transitional.dtd'>",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.phoenix-partyband.de"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tp/html4/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tr/1999/rec-html401-19991224/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tr/htm14/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3.org/tr/rec-html401/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http://www.w3c.org/tr/html4/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http:/www.w3.org/tr/html4/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" ""http:www.w3.org/tr/htm14/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" """">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""-//w3c//dtd html 4.01 transitional//en"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""../www.w3.org/tr/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http:// www.w3.org/tr/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://sky2.co.jp"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.gs-sh.de/tr/html4/frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.mountviewguesthouse.com"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.tobycreekoutfitters.com"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w.org/tr/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.ohtml4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/ html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/htm14/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html14/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4.01/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/ transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtdd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loosedtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/srtict.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/rec-html40//loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/rec-html40/strict.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/rec-html401/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr?html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3c.org/tr/html14/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3c.org/tr/rec-html40/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3org./tr/html4/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3org/tr/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en""""http://www.w3.org/tr/1999/rec-html401-19991224/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd html 4.01 transitional//en""""http://www.w3.org/tr/html40/loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 frameset//en"" ""http://www.w3.org/tr/xhtml/dtd/xhtml-1frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 frameset//en"" ""http://www.w3.org/tr/xhtml1-frameset.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 frameset//en"" ""xhtml1-f.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" "" http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd "">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" "" http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" """">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""./dtd/xhtml1/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""dtd/xhtml1-loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://store.pchome.com.tw/yeslife/"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://ww.w3.org/tr/xtml1/dtd/transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.ingensys.net"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.meetup.com/meetupxhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.rep.routledge.com:80/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.or g/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtm1/dtd/shtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1//dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/ xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhmtl1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtm1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml 1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transit ional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transition.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dt"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml11-loose.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml2/dtd/xhtml1-strict.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3c.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://wwww.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http:://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""xhtml1-transitional.dtd"" >",
            @"!doctype html public '-//w3c//dtd xhtml 1.0 transitional//en' ' http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd '>",
            @"!doctype html public '-//w3c//dtd xhtml 1.0 transitional//en' 'http://www.w3.org/tr/xhtml1/dtd/transitional.dtd'>",
            @"!doctype html public '-//w3c//dtd xhtml 1.0 transitional//en' 'http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd'>",
            @"!doctype html public '-//w3c//dtd xhtml 1.0 transitional//en'>",
            @"!doctype html public""-//w3c//dtd html 4.01 frameset//en""""http://www.w3.org/tr/html4/frameset.dtd"">",
            @"!doctype html public""-//w3c//dtd html 4.01 frameset//en""""http:www.k2.dion.ne.jp/~alpen/frameset.dtd"">",
            @"!doctype html public""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"!doctype html public""-//w3c//dtd html 4.01 transitional//en""""http://www.w3.org/tr/html4/loose.dtd"">",
            @"!doctype html public""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"!doctype html public""-//w3c//dtd xhtml 1.0 transitional//en""""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">"
            };
            foreach (var doctype in data)
            {
                var actual = CompatibilityMode.GetCompatibilityModeFromDoctype(doctype.Trim(new [] {'<','>','!'}));
                Assert.Equal(CompatibilityModeDoctype.LimitedQuirks, actual);
            }
        }

        [Fact]
        public void Test_CompatibilityMode_Quirks()
        {
            var data = new[]
            {
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2//en"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 final//en"">",
            @"<!doctype html public ""-//ietf//dtd html//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" >",
            @"<!doctype html public ""-//w3c//dtd html 4.01 frameset//en"">",
            @"<!doctype html public ""-//ietf//dtd html 2.0//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"">",
            @"<!doctype html public ""-//softquad software//dtd hotmetal pro 6.0::19990601::extensions to html 4.0//en"" ""hmpro6.dtd"">",
            @"<!doctype html public ""-//""aol hometown//html 3.0 transitional//en"">",
            @"<!doctype doctype public ""-//w3c//dtd html 4.0 transitional//en"">",
            @"<!doctype html public ""-//ietf//dtd html//en//2.0"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" >",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" system ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd""/>",
            @"<!doctype html public ""-//softquad//dtd hotmetal pro 4.0::19971010::extensions to html 4.0//en"" ""hmpro4.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/html40/loose.dtd"">",
            @"<!doctype html public '-//w3c//dtd html 4.01 transitional//en'>",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" ""http://www.w3.org/tr/rec-html40/frameset.dtd"">",
            @"<!doctype html public '-//w3c//dtd html 4.0 transitional//en'>",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" <html>",
            @"<!doctype html public ""-//ietf//dtd html 3.0//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" "" >",
            @"<!doctype html public ""-//ietf//dtd html 3.2//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/1998/rec-html40-19980424/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 draft//en"">",
            @"<!doctype html public>",
            @"<!doctype html public ""-//ietf//dtd html 3.0//en"" ""html.dtd"">",
            @"<!doctype html public ""-//netscape comm. corp.//dtd html//en"">",
            @"<!doctype html public ""-//sq//dtd html 2.0 hotmetal + extensions//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"" />",
            @"<!doctype html public ""-//ietf//dtd html 3.2 final//en"">",
            @"<!doctype html public ""-//ietf//dtd html//en//3.0"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 final//en"" ""http://www.w3.org/markup/wilbur/html32.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html40 loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd w3 html//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"" />",
            @"<!doctype html public ""-//ietf//dtd html 3.2//en"" ""html.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2//en"" ""hmpro6.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 frameset//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-frameset.dtd"" />",
            @"<!doctype html public""-//w3c//dtd html 4.0 transitional//en"">",
            @"<!doctype html public""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html public ""-//ietf//dtd html//en"" ""hmpro6.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 3.2 final//en"" ""hmpro6.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 frameset//en"" <html>",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" />",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"" <html>",
            @"<!doctype html public""-//w3c//dtd html 3.2//en"">",
            @"<!doctype html system>",
            @"<!doctype ""xmlns:xsl='http://www.w3.org/1999/xsl/transform'"">",
            @"<!doctype html public ""-//""aol hometown//html 3.0 transitional//fr"">",
            @"<!doctype html public ""-//sq//dtd html 2.0 hotmetal + extensions//en"" ""hmpro6.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html40/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-/w3c/dtd html 4.0 transitional/en"">",
            @"<!doctype html public '-//ietf//dtd html//en'>",
            @"<!doctype html public \""-//w3c//dtd html 4.0 transitional//en\"">",
            @"<!doctype>",
            @"<!doctype htm public ""-//w3c//dtd htm 4.0 transitional//en"">",
            @"<!doctype html ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public """"-//w3c//dtd xhtml 1.0 transitional//en"""" """"http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"""">",
            @"<!doctype html public ""-//""aol hometown//html 3.0 transitional//de"">",
            @"<!doctype html public ""-//ietf//dtd html 3.0//en//"">",
            @"<!doctype html public ""-//microsoft//dtd internet explorer 3.0 tables//en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" ""http://www.w3.org/tr/html4/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3c.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" />",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en ""http://www.w3.org/tr/html4/loose.dtd"""">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"" />",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" <html>",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" system ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public '-//w3c//dtd html 3.2//en'>",
            @"<!doctype html public -//w3c//dtd html 4.01 transitional//en>",
            @"<!doctype html public @@-//w3c//dtd html 3.2 final//en@@>",
            @"<!doctype html public \""-//w30//dtd w3 html 2.0//en\"">",
            @"<!doctype html public""-//w3c//dtd html 3.2 final//en"">",
            @"<!doctype html public=""-//w3c//dtd html 4.0 transitional//en"">",
            @"<!doctype ""=""&quot;"" public=""public"" html=""html"" http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd=""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"" 1.0=""1.0"" -//w3c//dtd=""-//w3c//dtd"" strict//en=""strict//en"" ="" "" xhtml=""xhtml"">",
            @"<!doctype ""html public""/>",
            @"<!doctype = ""html 4.01 transitional"">",
            @"<!doctype doctype public ""-//w3c//dtd html 4.0 transitional//cat"">",
            @"<!doctype doctype public ""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype doctype public ""-//w3w//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/transitional.dtd"">",
            @"<!doctype ht ml public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype ht@""<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype htlm public ""-//w3c//dtd xhtm 1.0 strict//en ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype htm public ""-//w3c//dtd htm 4.01 frameset//en"">",
            @"<!doctype htm public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype htm# public ""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html ""_//ietf//dtd html 3.0//en"">",
            @"<!doctype html american oldies ""-//w3c//dtd html 3.2//rm"">",
            @"<!doctype html lic ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html media ""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html puator"" content="""">",
            @"<!doctype html pubblic""-//w3c//dtd html 3.2//en"">",
            @"<!doctype html pubdivc ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//ietf//dtd html 2.0//en"" <html>",
            @"<!doctype html public ""-//ietf//dtd html 3.0//en"" ""c:\icspider\default.dtd"">",
            @"<!doctype html public ""-//ietf//dtd html 3.0//en//"" entity %>",
            @"<!doctype html public ""-//ietf//dtd html level 2//en//2.0"">",
            @"<!doctype html public ""-//ietf//dtd html//en"" />",
            @"<!doctype html public ""-//ietf//dtd html//en//4.2"" w.s.>",
            @"<!doctype html public ""-//netscape comm. corp.//dtd html//en"" >",
            @"<!doctype html public ""-//softquad software//dtd hotmetal pro 6.0::19990601::extensions to html 4.0//en"">",
            @"<!doctype html public ""-//w30//dtd w3 html 3.0//en"" -->",
            @"<!doctype html public ""-//w3c// dtd xhtml 1.0 frameset//en"" http://www.w3.org/tr/xhtml1/dtd/xhtml-frameset.dtd>",
            @"<!doctype html public ""-//w3c//dtd html 3.2 transitional//en""!>",
            @"<!doctype html public ""-//w3c//dtd html 3.2//en"" ! name: (marion/marion4h.htm) ! author: amy knotts/ssauter ! ! revision history: ! 12/8/99 ss ! ! !>",
            @"<!doctype html public ""-//w3c//dtd html 3.2//en"" >",
            @"<!doctype html public ""-//w3c//dtd html 3.2//en""-->",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en ""http""//www.w3.org/tr/rec-html40/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" ""_the_latest_version_/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" ""http://www.w3.org/tr/1998/rec-html40-19980424/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" ""http://www.w3.org/tr/rec-html140/frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" ""http://www.w3.org/tr/rec-html40/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" http://www.arteober.com"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 frameset//en"" http://www.w3.org/tr/rec-html40/frameset.dtd>",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en ""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en >",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://celestia.citeweb.net"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/html14/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/html4/transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-ht ml40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html-40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html40/loose"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd"" >",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html40/loose.dtd>",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html40/transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/rec-html401/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-frameset.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3.org/tr/xhtmll/dtd/xhtmll-strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://www.w3c.org/tr/html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" ""http://wwww.w3c.org/tr/html4/ctrict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"" @""<!--updated july 13, 2007-->",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"""" http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en""""http://www.w3.org/tr/rec-html40/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en""/>",
            @"<!doctype html public ""-//w3c//dtd html 4.0 transitional//en>",
            @"<!doctype html public ""-//w3c//dtd html 4.0//en"" <html>",
            @"<!doctype html public ""-//w3c//dtd html 4.01 frameset/en"" <html>",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional// <html>",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd""/>",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" @""<!--designed by steven sailer -->",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" @""<!--programmiert von robert dohmann-->",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" <html lang=""en"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" <html lang=""ja-jp"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" onload="""">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"" @@@@@""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en""-->",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en""/>",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en""n"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01 transitional//en""s ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en"""">",
            @"<!doctype html public ""-//w3c//dtd html 4.01//en""http://www.w3.org/tr/html4/strict.dtd"">",
            @"<!doctype html public ""-//w3c//dtd html 5.0//en"" />",
            @"<!doctype html public ""-//w3c//dtd html @""<!doctype html public ""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 @""<!-- saved from url=(0013)about:internet -->",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"" <html xmlns=""http://www.w3.org/1999/xhtml"" xml:lang=""en"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"" [ @""<!attlist a target cdata #implied>",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional// ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.ibm.com/data/dtd/v11/ibmxhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"" <html xmlns=""http://www.w3.org/1999/xhtml"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd""/>",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd>",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" ""xhtml1-transitional.dtd""[]>",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" <head profile=""http://gmpg.org/xfn/11"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd lang=en>",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" xmlns=""http://www.w3.org/1999/xhtml"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en"" â â ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0 transitional//en\ ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd xhtml 1.0"" transitional//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"">",
            @"<!doctype html public ""-//w3c//dtd@""<!doctype html public ""-//w3c//dtd html 4.0 transitional//en"">",
            @"<!doctype html public ""-//w3o//dtd w3 html 3.0//en"">",
            @"<!doctype html public ""-//w6c//dtd html 4.01 transitional//en"" />",
            @"<!doctype html public ""-//webtechs//dtd mozilla html//en"">",
            @"<!doctype html public ""html"">",
            @"<!doctype html public ""public"" ""-//w3c//dtd html 4.01//en""[http://www.w3.org/tr/html4/strict.dtd]>",
            @"<!doctype html public #-//w3c//dtd html 3.2//en#>",
            @"<!doctype html public &quot;-//w3c//dtd html 3.2//en&quot;>",
            @"<!doctype html public &quot;-//w3c//dtd html 4.0 transitional//en"">",
            @"<!doctype html public '-//w3c//dtd html 3.2 final//en'>",
            @"<!doctype html public '-//w3c//dtd html 4.0 transitional//en' 'http://www.w3.org/tr/rec-html40/loose.dtd'>",
            @"<!doctype html public -//w3c//dtd html 4.0 transitional//en>",
            @"<!doctype html public -//w3c//dtd xhtml 1.0 strict//en>",
            @"<!doctype html public <html>",
            @"<!doctype html public =""-//ietf//dtd html 4.0//it"">",
            @"<!doctype html public =""-//w3c//dtd html 3.2//en"">",
            @"<!doctype html public =""-//w3c//dtd html 4.0//en"">",
            @"<!doctype html public >",
            @"<!doctype html public @@-//w3c//dtd html 4.0//en@@>",
            @"<!doctype html public \""-//w3c//dtd html 4.0 transitional//en\"" >",
            @"<!doctype html public \""-//w3c//dtd html 4.01 transitional//en\"">",
            @"<!doctype html public \""-//w3c//dtd html 4.01//en\"" \""http://www.w3.org/tr/html4/strict.dtd\"">",
            @"<!doctype html public \""-//w3c//dtd html 4.01//en\"">",
            @"<!doctype html public por mafa""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html public -//w3c//dtd html 4.0 transitional//en>",
            @"<!doctype html public -//w3c//dtd html 4.01 transitional//en>",
            @"<!doctype html public â-//w3c//dtd xhtml 1.0 transitional//enâ âhttp://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtdâ>",
            @"<!doctype html public""-//w3c//dtd html 4.0 frameset//en"">",
            @"<!doctype html public=""-//ietf//dtd html 4.0//en"">",
            @"<!doctype html public=""-//w3c//dtd html 4.01 transitional//en"">",
            @"<!doctype html public=""-//w3c//dtd"" html 3=""2//en"">",
            @"<!doctype html pupflic ""-//ietf//dtd html//en"">",
            @"<!doctype html puplic ""-//w3c//dtd html 4.01//en"">",
            @"<!doctype html.public ""-//w3c//dtd html 3.2//en"">",
            @"<!doctype htmll public ""-//w3c//dtd htmll 3.2 final//en"">",
            @"<!doctype htmll public ""-//w3c//dtd htmll 4.0 transitional//en"">",
            @"<!doctype htmll public ""-w3c//dtd xhtmll 1.0 strict//en"" ""http:www.w3.org/tr/xhtmll1/dtd/xhtmll/1-strict.dtd"">",
            @"<!doctype htmlpublic ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/1999/rec-html401-19991224/loose.dtd"">",
            @"<!doctype htmlpublic ""-//w3c//dtd xhtml 1.0 strict//en"" ""http:www.w3.org/tr/htmll/dtd/htmll-strict"">",
            @"<!doctype php public ""-//w3c//dtd php 4.0 transitional//en"">",
            @"<!doctype php public ""-//w3c//dtd php 4.01 transitional//en"">",
            @"<!doctype php public ""-//w3c//dtd xphp 1.0 transitional//en"" ""http://www.w3.org/tr/xphp1/dtd/xphp1-transitional.dtd"">",
            @"<!doctype public ""-//w3c//dtd html 4.01 transitional//en"" ""http://www.w3.org/tr/html4/loose.dtd"">",
            @"<!doctype shtmll public ""-//w3c//dtd shtmll 4.0 transitional//en"">",
            @"<!doctype table public ""-//w3c//dtd xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype xhtml 1.0 strict//en"" ""http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd"">",
            @"<!doctype xhtml public ""-//w3c//dtd xhtml 1.1//en"" ""http://www.w3.org/tr/xhtml11/dtd/xhtml11.dtd"">",
            @"<!doctype@""<!doctype html public ""-//w3c//dtd html 3.2//en"">",
            @"<!doctypel public ""-//w3c//dtdl 4.0 transitional//en"">"
            };
            foreach (var doctype in data) {
                var actual = CompatibilityMode.GetCompatibilityModeFromDoctype(doctype.Trim(new[] { '<', '>', '!' }));
                Assert.Equal(CompatibilityModeDoctype.Quirks, actual);
            }
        }


    }
}
