namespace JsParser.Hash
{
    public enum JsKeyword
    {
        CUSTOM = 0,       // Not recognized

        New = 3,
        Enum = 4,
        Super = 5,
        In = 7,
        Int = 8,
        Short = 10,
        Delete = 11,
        Default = 12,
        Debugger = 13,
        Interface = 14,
        Instanceof = 15,
        Return = 16,
        If = 17,
        Function = 18,
        Else = 19,
        Final = 20,
        Public = 21,
        Finally = 22,
        Char = 24,
        Do = 27,
        Goto = 29,
        Float = 30,
        Double = 31,
        Private = 32,
        For = 33,
        Protected = 34,
        Class = 35,
        Native = 36,
        Synchronized = 37,
        Long = 39,
        Const = 40,
        Static = 41,
        Continue = 43,
        This = 44,
        Throw = 45,
        Throws = 46,
        Try = 48,
        Case = 49,
        Catch = 50,
        Package = 52,
        Transient = 54,
        Break = 55,
        Switch = 56,
        With = 59,
        While = 60,
        Export = 61,
        Extends = 62,
        Void = 64,
        Typeof = 66,
        Boolean = 67,
        Volatile = 68,
        Byte = 69,
        Import = 71,
        Var = 73,
        Implements = 75,
        Abstract = 78
    }
}